services:

  cutlery:
    depends_on:
      - waiter
    build: .
    environment:
      IP: "cutlery"
      WAITER_IP: "waiter"
      WAITER_PORT: "3000"
    entrypoint: [ "./cutlery" ]
    #container_name: cutlery
    networks:
      - free_wifi
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr

  philosopher:
    depends_on:
      - waiter
    build: .
    environment:
      IP: "philosopher"
      WAITER_IP: "waiter"
      WAITER_PORT: "3000"
    entrypoint: [ "./philosopher" ]
    #container_name: philosopher
    networks:
      - free_wifi
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr

  waiter:
    build: .
    command: ./waiter
    environment:
      WAITER_IP: "172.27.0.2"
      WAITER_PORT: "3000"
      WAITER_HTTP_PORT: "3001"
      VISITORS: "3"
    ports:
      - "3000:3000"
      - "3001:3001"
    entrypoint: [ "./waiter" ]
    expose:
      - 3001
      - 3000
    container_name: waiter
    networks:
      free_wifi:
        ipv4_address: 172.27.0.2

networks:
  free_wifi:
    name: free_wifi
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
